CREATE DATABASE Imobiliaria_DDL;

GO
USE Imobiliaria_DDL;

CREATE TABLE Cliente (
	IdCliente INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(255) NOT NULL,
	Telefone CHAR(11) NOT NULL,
	CPF CHAR (11) NOT NULL UNIQUE,
);

CREATE TABLE Situacao (
	IdSituacao INT PRIMARY KEY IDENTITY,
	TipoSituacao VARCHAR(255) NOT NULL,
);

CREATE TABLE Aluguel (
	IdAluguel INT PRIMARY KEY IDENTITY,
	Endereco VARCHAR(255) NOT NULL,
	Valor VARCHAR(255) NOT NULL,
	DataVencimento VARCHAR(255) NOT NULL,
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente),
	IdSituacao INT FOREIGN KEY REFERENCES Situacao(IdSituacao),
);
GO
